# Generated by Django 5.1.5 on 2025-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(blank=True, choices=[('', 'Unknown'), ('choice 1', 'Choice 1'), ('choice 2', 'Choice 2'), ('choice 3', 'Choice 3')], default='', max_length=30)),
            ],
        ),
    ]
